### PR TITLE
fix auth way of deps

### PR DESCRIPTION
**Pull request by Nikolay-Kha**
'git, "git@github.com:something"' scheme require github authorization via ssh keys. 
'git://github.com/something' scheme allows clone public repos without ssh keys in system and this is more suitable for public repos.

### CODE REVIEW

**Comment by sanmiguel** [comment]
Thanks @Nikolay-Kha !

Could you please also apply the same changes to `rebar.config.lock`?

**Comment by Nikolay-Kha** [comment]
@sanmiguel sure thing.
It's done.

**Comment by sanmiguel** [comment]
Unfortunately that was a step too far....

The remote address for each dependency in `rebar.config.lock` must match the ones in `rebar.config`, or it will cause issues with how rebar checks dependencies are checked out to the correct version.

**Comment by sanmiguel** [comment]
I was wrong, this doesn't appear to cause any of the problems I thought.

Thanks @Nikolay-Kha

**Pull request merged**
