### PR TITLE
Add mesos erlang

### PR DESCRIPTION
**Pull request by Nikolay-Kha**
and remove mesos-executor-bindings

### CODE REVIEW

**Comment by platon** [comment]
LGTM :+1:

**Comment by sanmiguel** [comment]
I've pushed a couple of minor fixes, but I'm having weird issues getting the executor to start in a framework. I'm using the vagrant image from https://github.com/basho-labs/riak-mesos and have built the executor by going to `/vagrant/framework/riak-mesos-executor/` and running `make tarball`. I've selected that package in `/etc/riak-mesos/config.json` to install, and the scheduler has picked it up fine, but:

 - when it starts the node, the executor start date in Mesos UI is `47 years ago`
 - it never gets beyond `STARTING` state in Mesos

I'm investigating the status update thing, but @platon and @Nikolay-Kha do you have any ideas about the start-date problem?

**Comment by Nikolay-Kha** [comment]
@platon should we try to update uuid in status update?

**Comment by sanmiguel** [comment]
Am I right in thinking that a status update without a UUID should not be acknowledged by the scheduler, but those with a UUID should be acknowledged?

**Comment by Nikolay-Kha** [comment]
@sanmiguel https://github.com/apache/mesos/blob/master/include/mesos/v1/mesos.proto#L1447-L1455

**Comment by platon** [comment]
Latest changes should fix the problem with incorrect date in Mesos.

**Comment by sanmiguel** [comment]
Thanks! Testing them now.

**Comment by sanmiguel** [comment]
OK, as discussed - @platon and @Nikolay-Kha to look at splitting out some of the logic from `launch_task/3` into `acknowledged/3`, so that we don't just assume the scheduler knows what's going on.

**Comment by Nikolay-Kha** [comment]
@sanmiguel, check it now please. Now it should work. 
screenshot from 2016-07-17 00 10 45

**Comment by platon** [comment]
LGTM :+1:

**Comment by sanmiguel** [comment]
@Nikolay-Kha Looking great!

Something I would mention though is `riak_mesos_executor:create_task_status/4` and `riak_mesos_executor:update_task_status/3,4`: I think it would be more idiomatic Erlang to have their signatures defined as:

``` erlang
create_task_status(ExecutorInfo, TaskId, AgentId, State) ->
... % and:
update_task_status(ExecutorInfo, TaskStatusState, State) ->
... % and:
update_task_status(ExecutorInfo, TaskStatusState, Data, State) ->
```

as it is `State` that gets modified and returned.

**Comment by Nikolay-Kha** [comment]
@sanmiguel Fixed.

**Comment by sanmiguel** [comment]
Thanks @Nikolay-Kha ! This looks great, merging it now.

**Pull request merged**
